### PR TITLE
Automate React storybook links

### PR DESCRIPTION
**Pull request by josepmartins**
Generate storybook links in PRC components from the static file: https://primer.style/react/storybook/stories.json

### Stories id and links

Each story contains an `id` with the following structure:

`[field]-[componentID(without underscore)]--[story]`

E,g. `button` id: `components-button--default-button`

Given this `id` the PR generates the following link to the story: `/react/storybook?path=/story/` + `id`

Based on the example, PRC button will generate: http://primer.style/react/storybook?path=/story/components-button--default-button

### Solution

- Fetching `stories.json` data when `React` components.
- Find `componentId` within stories.json `id's` and use matching items as links.

#### Edge cases and fixes

The `stories.json` file isn't configurable, and that creates some edge cases to take into account (ideally we will add the `componentID` to have a perfect match):

- The `id` includes other `componentID`:
	- E,g. `components-segmentedcontrol-segmentedcontrol-iconbutton--playground` contains `button`. 
	- The `avatar` component doesn't have stories, but `avatarstack` does. When looking for `avatar` stories it will match the `avatarstack-avatar-` stories.
	- Fix: match an `id` that contains {"-" + componentID + "--default"} to avoid conflicts
- Components with a deprecated version:
	- E,g. Looking for deprecated `button` vs `button` stories will match `button` stories instead of deprecated ones.
	- Fix: Conditionally look for `deprecated` if `status` = `deprecated`

### Done
- [x] Improving search to avoid conflicts. E,g: When `componentID` is `select`, avoid matching the search with `components-actionlist-examples--single-**select**ion`
- [x] Add conditional when `status` = `deprecated`
- [x] Fetch data only when React pages.
- [x] Use the first storybook `id` from the fetched data. E,g: When `componentID` is `button` it uses `components-button--default-button`
- [x] Used if there's no `storybook` provided on the frontmatter

#### Related

- @langermank is working on adding `default` missing stories that will facilitate fetching data and avoid edge cases above here: https://github.com/github/primer/issues/1488
- https://github.com/primer/react/pull/2507

### CODE REVIEW

**Review by broccolinisoup — COMMENTED** [review]
Looks great to me ✨ Is it possible to give an example of how we will import the storybook url into the docs file? Like how 
would `storybook: '/react/storybook?path=/story/components-actionmenu'` look like when we start using the stories.json? 👀 

Also, I guess we need to be mindful about the timing of this PR's merge. Because currently not all stories have `Default` story.   
We will probably have to wait for us to get all components' stories on the same format before realising this if I understand correctly

**Comment by josepmartins** [comment]
@broccolinisoup 👋 🥦 

> Looks great to me ✨ Is it possible to give an example of how we will import the storybook URL into the docs file? Like how would storybook: '/react/storybook?path=/story/components-actionmenu' look like when we start using the stories.json? 👀

The idea here is to avoid importing these URLs and to generate them on the client side for pages using the Doctocat layout. We follow a similar approach with the component descriptions by taking them from the `component-metadata` repo [here].(https://github.com/primer/doctocat/blob/d1ace431eb0391cb90577e39d73f21bbe115164f/theme/src/components/layout.js#L55). 

> Also, I guess we need to be mindful about the timing of this PR's merge. Because currently not all stories have Default story. We will probably have to wait for us to get all components' stories on the same format before realising this if I understand correctly

👍 agree! @langermank is working on that ✨ Anyways, this shouldn't conflict with the actual storybook links that have been added manually in the PRC docs. If there's no `--default` story or if there's a manual link, it doesn't generate a new one or overwrite it.

**Comment by colebemis** [comment]
We're automatically generating links to the storybook in the new docs here: https://github.com/primer/design/blob/main/src/layouts/react-component-layout.tsx#L185

I'm hesitant to add this logic to Doctocat since Doctocat should be more generic, and this is a very specific use case.

**Review by colebemis — COMMENTED** [review]
We're automatically generating links to the storybook in the new docs here: https://github.com/primer/design/blob/main/src/layouts/react-component-layout.tsx#L185

I'm hesitant to add this logic to Doctocat since Doctocat should be more generic, and this is a very specific use case.

@josepmartins How do you feel about closing this PR since we have this feature working in the new docs?

**Comment by josepmartins** [comment]
> We're automatically generating links to the storybook in the new docs here: https://github.com/primer/design/blob/main/src/layouts/react-component-layout.tsx#L185
> 
> I'm hesitant to add this logic to Doctocat since Doctocat should be more generic, and this is a very specific use case.
> 
> @josepmartins How do you feel about closing this PR since we have this feature working in the new docs?

makes sense 👍

**Pull request closed without merging**
