### PR TITLE
Upgrade to styled-components v5

### PR DESCRIPTION
**Pull request by dcastil**
🎉 

Release: https://github.com/styled-components/styled-components/releases/tag/v5.0.0
Migration docs: https://styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v5

### CODE REVIEW

**Comment by dcastil** [comment]
Hmmm could someone tell me what made the deployment fail? I don't have permission to access the build logs unfortunately.

**Comment by dcastil** [comment]
Damn, I didn't even notice. Thanks for investigating, @colebemis! Seems like some styles are applied and some not. I'll try to figure it out. But there shouldn't be any breaking changes to the `StylesheetManager`, it might be a bug in styled-components.

**Comment by dcastil** [comment]
The `StylesheetManager` fix https://github.com/styled-components/styled-components/pull/3159 was merged just now. Looks like we can make the upgrade happen after the next release of styled-components. 😊

**Comment by mxstbr** [comment]
~10% faster! 😍 

Screenshot 2020-11-02 at 07 27 58

Screenshot 2020-11-02 at 07 28 15

**Pull request closed without merging**
