### PR TITLE
Import `NavList` from main bundle

### PR DESCRIPTION
**Pull request by broccolinisoup**
We are removing `NavList` from the drafts bundle in the next major release in this [PR](https://github.com/primer/react/pull/3260) and because we are removing it, CI fails on the PR. (https://github.com/primer/react/actions/runs/5582895864/jobs/10202654279?pr=3260) 

I update the path to import it from the main bundle.

### CODE REVIEW

**Review by joshblack — COMMENTED** [review]
Seeing this error from CI:

```
warning "export 'NavList' was not found in '@primer/react'
```

Does the dependency need to be updated here: https://github.com/primer/doctocat/blob/main/theme/package.json#L37 potentially to the version which includes it? Or is there some other shenanigans going on here with Gatsby 😅

**Comment by mperrotti** [comment]
@broccolinisoup - it looks like Doctocat is on a really old version of `@primer/react`. `NavList` should be available in the main bundle once we update 🙂

**Comment by broccolinisoup** [comment]
@mperrotti @joshblack Sorry, this is my ignorance 😬 I didn't even think of checking back - I just assumed that will work. Let me try upgrading primer/react -  I know @josepmartins has some issues with upgrading to the latest so it might not be very straightforward

**Comment by mperrotti** [comment]
@josepmartins - the deprecated one is going away when we release v36 later this quarter 🙁 

Let me know if you want to pair on the upgrade. I suspect it has something to do with mismatched versions of React.

**Comment by mperrotti** [comment]
Should we add a "blocked" label to this? We're blocked until we can upgrade Gatsby and React.

cc @josepmartins @broccolinisoup

**Comment by broccolinisoup** [comment]
@mperrotti That sounds good to me! I added the label! Although this PR is blocked itself but it is not blocking [v36 PR I mentioned in the description](https://github.com/primer/react/pull/3260) anymore - we will keep the NavList in the draft bundle until we figure this out.

**Pull request closed without merging**
