### PR TITLE
Move header links info to siteMetadata

### PR DESCRIPTION
**Pull request by bolonio**
## Context

The theme hardcodes the word `Primer` in the header before the project short name defined by `siteMetadata.shortName`. You can see in [the `header.js` component](https://github.com/primer/doctocat/blob/main/theme/src/components/header.js#L57).

An screenshot of the header in the doctocat theme

This PR moves the header links info (logo and main link) to siteMetadata.

### Related Issue

- https://github.com/primer/doctocat/issues/493

### CODE REVIEW

**Comment by lesliecdubs** [comment]
@broccolinisoup since you're on FR this week, would you be willing to review this PR? Thank you! 🙏🏻

**Review by camertron — APPROVED** [review]

**Comment by bolonio** [comment]
@broccolinisoup @lesliecdubs Thanks for the review. I started this PR with my `@github.com` email but I don't have access to that user anymore. Could you please merge it? Thanks :)

**Comment by broccolinisoup** [comment]
> 

Oh! Thanks for letting us know. Best of luck @bolonio  👋🏼

**Comment by broccolinisoup** [comment]
> @broccolinisoup @lesliecdubs Thanks for the review. I started this PR with my `@github.com` email but I don't have access to that user anymore. Could you please merge it? Thanks :)

Oh! Thanks for letting us know. Best of luck @bolonio 👋🏼

**Pull request merged**
