### PR TITLE
Add vertical align middle to images in table

### PR DESCRIPTION
**Pull request by siddharthkp**
Can remove this file in primer/react: https://github.com/primer/design/blob/main/src/@primer/gatsby-theme-doctocat/components/table.js

For: https://github.com/primer/design/pull/192

image

### CODE REVIEW

**Comment by siddharthkp** [comment]
Still relevant :)

**Comment by siddharthkp** [comment]
@colebemis Can I get eyes on this one :)

**Review by colebemis — APPROVED** [review]
🚢

**Comment by siddharthkp** [comment]
Vercel deploys are failing, but we don't use vercel anymore, so going to ignore that :)

**Pull request merged**
